### ISSUE TITLE
Support for Class-Style-Components

### ISSUE THREAD

**Issue by anotherHoffmann** [davestewart/vue-enums#1]
Hi Dave,
can you add Support for Class-Style-Components? If it already exits, can you add an example to the readme?

**Comment by anotherHoffmann** [comment]
Solved it myself. It is not pretty, but you can add 
`(this.$options as any).enums = {INSERT_ENUM_HERE};`
to your constructor.

**Comment by davestewart** [comment]
Ah, sweet!

FWIW, I realised the problem I'm solving here is static data, then found another package that does the same thing, so I submitted a PR with the features from this package:

https://github.com/wagerfield/vue-static-data/pull/3

Unfortunately, no response yet!
